# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2018-12-05 01:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clickevent',
            name='update',
        ),
        migrations.AddField(
            model_name='clickevent',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
